Client library update for V2 Dunning Campaign API enhancements
recurly/recurly-client-net pull request #664
Opened 2021-10-18 19:18 UTC by sunnyw1212

Add dunning_campaign_id to Account, Invoice, and Plan
PUT v2/dunning_campaigns/{dunning_campaign_id}/bulk_update

2021-10-21 21:50 UTC, judith approved these changes

2021-10-22 15:36 UTC, douglasmiller requested changes

2021-10-22 15:36 UTC, douglasmiller commented on Library/DunningCampaign.cs
> +    public List<string> PlanCodes { get; private set;}
I think that we want to make this private as there is no reason to expose the availability of this variable to the developer. It is used solely as a storage location between `BulkUpdate` being called and the `WriteBulkUpdateXML` method being executed.

```suggestion
    private List<string> PlanCodes { get; private set;}
```

2021-10-22 15:36 UTC, douglasmiller commented on Library/DunningCampaign.cs
> +      foreach (string planCode in PlanCodes) {
Nit: C# puts opening curly braces on a new line

```suggestion
      foreach (string planCode in PlanCodes)
      {
```

2021-10-22 15:36 UTC, douglasmiller commented on Library/List/DunningCampaignList.cs
> +    public class DunningCampaignList : RecurlyList<DunningCampaign>
Did we determine that the API will return a pager shaped response even though we have a limit on the total number of dunning campaigns?

2021-10-22 15:46 UTC, jguidry-recurly commented on Library/Interval.cs
> +  public class Interval : RecurlyEntity
Do you think we should call it `DunningInterval` to keep these classes/files grouped? Given the reference to email template, it's a bit more specific than a generic interval class. Minor nit.

2021-10-22 16:47 UTC, sunnyw1212 commented on Library/Interval.cs
> +  public class Interval : RecurlyEntity
hmm its's a good point, but we're calling it `Interval` in all the other client libs and passing it back as `interval` in the xml response. 

not sure if it's worth going back and changing that name everywhere at this point?

2021-10-22 17:30 UTC, sunnyw1212 commented on Library/DunningCampaign.cs
> +    public List<string> PlanCodes { get; private set;}
yep good call - fixed

2021-10-22 17:30 UTC, sunnyw1212 commented on Library/DunningCampaign.cs
> +      foreach (string planCode in PlanCodes) {
fixed

2021-10-22 17:49 UTC, jguidry-recurly commented on Library/Interval.cs
> +  public class Interval : RecurlyEntity
On further reflection, agree. Remaining consistent (within reason) across client implementations is a good priority and, as you point out, the naming is already blessed in the underlying schema.

I actually steered Amanda toward `DunningInterval` [on the Python client yesterday](https://github.com/recurly/recurly-client-python/pull/515/files#diff-29341c2217f213f31f173ac977f56d2eba7834da42c33b76ed85fb8673e82920R525) though. @amandamfielding Do you have any leaning on this? I'm thinking that it should made to match.

2021-10-22 19:14 UTC, sunnyw1212 commented on Library/List/DunningCampaignList.cs
> +    public class DunningCampaignList : RecurlyList<DunningCampaign>
yes, as far as i can tell we are

2021-10-22 22:03 UTC, douglasmiller approved these changes
👍🏼 

Deferring to @jguidry-recurly for final approval.

2021-10-25 16:31 UTC, amandamfielding commented on Library/Interval.cs
> +  public class Interval : RecurlyEntity
@jguidry-recurly I think we should stay consistent and i'll make the change in the python library to call it `Interval`

2021-10-25 22:13 UTC, judith commented on Library/Interval.cs
> +  public class Interval : RecurlyEntity
Actually after discussing it further we decided that it makes sense to call the resource for the `interval` in the XML response `DunningInterval` in the client libraries as it will match what is happening in the API V3/V4 client libraries.

2021-10-26 14:29 UTC, jguidry-recurly commented on Library/DunningCycle.cs
> +                case "applies_to_manual":
Should this be `applies_to_manual_trial`? I encountered [a problem](https://github.com/recurly/recurly-client-python/pull/515#discussion_r733037553) with this on the Python client.

2021-10-26 15:22 UTC, sunnyw1212 commented on Library/DunningCycle.cs
> +                case "applies_to_manual":
good catch - fixed

2021-10-26 15:35 UTC, judith approved these changes

2021-10-26 15:40 UTC, jguidry-recurly approved these changes

2021-10-26 22:17 UTC, douglasmiller approved these changes

2021-10-27 00:48 UTC, merged